#!/bin/bash
################################################################################
# sudo apt install git-core
# git clone https://github.com/plx01/lmssetup ~/01l
# sudo chmod +x ~/01l/lmslinode.sh
# ~/01/lmslinode.sh
$OE_USER = "canvas"
sudo apt update && sudo apt upgrade
cd

#-------------------------
# 1. Install Apache
# 1
sudo apt install dirmngr gnupg
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
sudo apt install apt-transport-https ca-certificates
# 2
sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger bionic main > /etc/apt/sources.list.d/passenger.list'
sudo apt update
# 3
sudo apt-get install -y libapache2-mod-passenger
sudo apt install -y apache2 apache2-dev passenger  && passenger -v
# 4
sudo a2enmod passenger rewrite  && sudo systemctl restart apache2

#-------------------------
# 2 Install PostgreSQL
# 1
sudo apt-get install postgresql
# 2
sudo -u postgres createuser canvas --no-createdb --no-superuser --no-createrole --pwprompt
# 3
sudo -u postgres createdb canvas_production --owner=canvas
# 4
sudo -u postgres psql -c "alter user $USER with superuser" postgres

#-------------------------
# 3 Install Ruby
# 1
sudo apt install software-properties-common
sudo add-apt-repository ppa:brightbox/ruby-ng
sudo apt update
# 2
sudo apt-get install ruby2.6 ruby2.6-dev zlib1g-dev libxml2-dev libsqlite3-dev postgresql libpq-dev  libxmlsec1-dev curl make g++
# 3
sudo gem install bundler --version 2.2.17

#-------------------------
# 4 Install Node.js and Yarn
# 1 Install Node.js.
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install nodejs
sudo npm install -g npm@latest
# 2 Install Yarn, a package manager used in the Canvas installation process.
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
sudo apt-get update && sudo apt-get install yarn=1.19.1-1
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt-get install python

#-------------------------
# 5 Install Canvas
# 1
sudo apt-get install git-core
# 2
git clone https://github.com/instructure/canvas-lms.git ~/canvas
# 3
cd ~/canvas  && git checkout stable
# 4-5
sudo mkdir -p /var/canvas  && sudo chown -R $USER /var/canvas
sudo cp -R ~/canvas /var  && cd /var/canvas
# 6
bundle config set path 'vendor/bundle'
bundle config set --local without 'pulsar'
sudo chown -R $USER /home/$USER  && sudo chown -R $USER /var/canvas
bundle install
# 7
sudo chown -R $USER /home/$USER  && sudo chown -R $USER /var/canvas
yarn install
sudo systemctl restart apache2

#-------------------------
# 6 Set Up the Canvas Configuration Files
# 1
for config in amazon_s3 database delayed_jobs domain file_store outgoing_mail security external_migration; do cp config/$config.yml.example config/$config.yml; done
sudo apt install nano

sudo nano /var/canvas/config/dynamic_settings.yml
# 2
sudo nano /var/canvas/config/database.yml
# 3
sudo nano /var/canvas/config/domain.yml
# 4
sudo nano /var/canvas/config/outgoing_mail.yml
# 5
sudo nano /var/canvas/config/security.yml

# Generate the Canvas Assets and Data
# 1
mkdir -p log tmp/pids public/assets app/stylesheets/brandable_css_brands
touch app/stylesheets/_brandable_variables_defaults_autogenerated.scss
touch Gemfile.lock  && touch log/production.log
# 2
sudo chown -R $USER config/environment.rb log tmp public/assets app/stylesheets/_brandable_variables_defaults_autogenerated.scss app/stylesheets/brandable_css_brands Gemfile.lock config.ru
# 3
# snapshot 2
yarn install
# 4
cd /var/canvas
RAILS_ENV=production bundle exec rake db:reset_encryption_key_hash
RAILS_ENV=production bundle exec rake canvas:compile_assets
# Subsequent Updates (NOT NEEDED FOR INITIAL DEPLOY)
# RAILS_ENV=production bundle exec rake brand_configs:generate_and_upload_all
sudo systemctl restart apache2
# 5
sudo chown -R $USER public/dist/brandable_css
# 6
RAILS_ENV=production bundle exec rake db:initial_setup
# 7
# sudo chown -R $USER /home/$USER  && sudo chown -R $USER /var/canvas
# sudo adduser --disabled-password --gecos canvas canvasuser
# sudo chown canvasuser config/*.yml  && sudo chmod 400 config/*.yml
sudo chown canvas config/*.yml  && sudo chmod 400 config/*.yml
# 0
# sudo a2dismod passenger rewrite  && sudo a2enmod passenger rewrite
sudo systemctl restart apache2
# 8
sudo ln -s /var/canvas/script/canvas_init /etc/init.d/canvas_init
sudo update-rc.d canvas_init defaults
sudo /etc/init.d/canvas_init start

# Configure Apache for Canvas
# 1
# sudo unlink /etc/apache2/sites-enabled/000-default.conf
# 2-3
# sudo cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/canvas.conf  && sudo nano /etc/apache2/sites-available/canvas.conf
git clone https://github.com/plx01/lmssetup ~/01l
sudo cp ~/01l/canvas.conf /etc/apache2/sites-available/canvas.conf  && sudo nano /etc/apache2/sites-available/canvas.conf
sudo cp ~/01l/passenger.conf /etc/apache2/mods-available/passenger.conf  && sudo nano /etc/apache2/mods-available/passenger.conf
# sudo a2dismod passenger rewrite  && sudo a2enmod passenger rewrite
sudo systemctl restart apache2
# 4
sudo ufw enable  && sudo ufw status
sudo ufw allow http
# sudo ufw allow https
# sudo ufw deny https
sudo ufw reload  && sudo ufw status
# 5
sudo a2dissite 000-default  && sudo systemctl restart apache2
# sudo a2ensite 000-default  && sudo systemctl restart apache2
# sudo a2dissite canvas  && sudo systemctl restart apache2
# sudo a2ensite canvas  && sudo systemctl restart apache2
sudo a2dissite canvas  && sudo a2ensite canvas  && sudo systemctl restart apache2
curl http://phucenter.net/
# 6
sudo systemctl restart apache2
sudo systemctl status apache2.service

